name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Build and test with Maven
      run: cd backend && ./mvnw -B verify
      
    - name: Upload Jacoco coverage report
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: backend-coverage-report
        path: backend/target/site/jacoco/
        retention-days: 5

  frontend-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'
        
    - name: Install pnpm
      run: npm install -g pnpm
        
    - name: Install dependencies
      run: cd frontend && pnpm install
      
    - name: Run tests with coverage
      run: cd frontend && pnpm test -- --coverage
      
    - name: Upload coverage report
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: frontend-coverage-report
        path: frontend/coverage/
        retention-days: 5